version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=AKIA2U3K53D5XC5SXD6W
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_PUBLIC_BUCKET_NAME=cats-images-from-api
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"