version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=yuri
      - POSTGRES_PASSWORD=3012
      - POSTGRES_DB=cats_db
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=yuri
      - POSTGRES_PASSWORD=3012
      - POSTGRES_DB=cats_db
    ports:
      - "5432:5432"